22-Sep-23 14:45:59 - ERROR - Uncaught exception
Traceback (most recent call last):
  File "/home/developer/Documents/repository/my-unicorn/main.py", line 92, in <module>
    main()
  File "/home/developer/Documents/repository/my-unicorn/main.py", line 59, in main
    method()
  File "/home/developer/Documents/repository/my-unicorn/cls/AppImageDownloader.py", line 274, in download
    print(f"Downloaded {self.appimage_name}")
OSError: [Errno 5] Input/output error
